# Generated by Django 5.1 on 2024-09-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chaivariety",
            old_name="type",
            new_name="chai_type",
        ),
    ]
