# Generated by Django 5.1 on 2024-09-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_chaicertificate_chaireview_stores"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "chai_varieties",
                    models.ManyToManyField(
                        related_name="store", to="myApp.chaivariety"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Stores",
        ),
    ]
