# Generated by Django 5.1 on 2024-09-18 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0005_store_delete_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaicertificate",
            name="issue_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
